#!/usr/bin/env python3
"""
PureBrain Subdomain Router
==========================
Manages flat subdomain routing for *.purebrain.ai customer portals.

Architecture:
- Cloudflare tunnel catches all *.purebrain.ai traffic → nginx on localhost:8099
- nginx proxies based on hostname to correct backend
- Each customer gets: {ainame}{humanfirstname}.purebrain.ai → container portal URL

Routes file: /home/jared/purebrain_routes.json
  {
    "keenjared": {
      "subdomain": "keenjared",
      "container": "aiciv-12",
      "portal_url": "https://keenjared.ai-civ.com",
      "human_email": "jared@puretechnology.nyc",
      "human_name": "Jared Sanborn",
      "civ_name": "keen",
      "created_at": "2026-03-04T..."
    }
  }

Usage:
  python3 subdomain_router.py add keenjared https://keenjared.ai-civ.com aiciv-12
  python3 subdomain_router.py list
  python3 subdomain_router.py remove keenjared
  python3 subdomain_router.py reload-nginx
  python3 subdomain_router.py status

Or import and call add_customer_route() from purebrain_log_server.py
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ROUTES_FILE = Path('/home/jared/purebrain_routes.json')
NGINX_CONF_DIR = Path('/etc/nginx/conf.d')
NGINX_CUSTOMER_CONF = NGINX_CONF_DIR / 'purebrain-customer-portals.conf'
NGINX_MAIN_CONF = NGINX_CONF_DIR / 'purebrain-main.conf'
TUNNEL_ID = 'fa55839c-e753-4a96-935c-cc58cf24b4b8'

# nginx listens on this port; cloudflared forwards *.purebrain.ai here
NGINX_PORT = 8099

# Admin portal (portal.purebrain.ai → local port 8097)
ADMIN_PORTAL_PORT = 8097


# ---------------------------------------------------------------------------
# Routes file management
# ---------------------------------------------------------------------------

def load_routes() -> dict:
    """Load routing table from JSON file."""
    if not ROUTES_FILE.exists():
        return {}
    try:
        return json.loads(ROUTES_FILE.read_text())
    except Exception:
        return {}


def save_routes(routes: dict):
    """Save routing table to JSON file."""
    ROUTES_FILE.write_text(json.dumps(routes, indent=2))


# ---------------------------------------------------------------------------
# nginx config generation
# ---------------------------------------------------------------------------

def _generate_customer_block(subdomain: str, portal_url: str) -> str:
    """Generate nginx server block for a single customer subdomain.

    Routes {subdomain}.purebrain.ai → portal_url (Witness container URL).
    Preserves WebSocket upgrade headers (portal uses WebSockets for live terminal).

    Uses set $backend with resolver to avoid nginx startup DNS resolution failure
    for external upstream hostnames that may not exist yet.
    """
    # Parse scheme and host from portal_url for set $backend pattern
    # e.g. https://keenjared.ai-civ.com → scheme=https, backend_var=https://keenjared.ai-civ.com
    return f"""
# Customer: {subdomain}.purebrain.ai → {portal_url}
server {{
    listen {NGINX_PORT};
    server_name {subdomain}.purebrain.ai;

    # Use Cloudflare/Google DNS for resolving external Witness container hostnames
    # 'valid=60s' re-resolves every minute (handles dynamic IPs)
    resolver 1.1.1.1 8.8.8.8 valid=60s ipv6=off;

    # Increase timeouts for long-lived WebSocket connections
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

    location / {{
        # Use variable to delay DNS resolution to request time (not nginx startup)
        set $backend "{portal_url}";
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Purebrain-Subdomain "{subdomain}";
        proxy_buffering off;
        proxy_cache off;
    }}
}}
"""


def _generate_nginx_conf(routes: dict) -> str:
    """Generate the full nginx conf.d file for all customer routes."""
    header = f"""# PureBrain Customer Portal Routes
# Generated by subdomain_router.py — DO NOT EDIT MANUALLY
# Last updated: {datetime.now(timezone.utc).isoformat()}
#
# Architecture: cloudflared *.purebrain.ai → nginx:{NGINX_PORT} → Witness containers
# Manage via: python3 /home/jared/projects/AI-CIV/aether/tools/subdomain_router.py

"""
    blocks = [header]

    # Catch-all: unknown subdomains → 404 with helpful message
    blocks.append(f"""
# Catch-all for unknown *.purebrain.ai subdomains
server {{
    listen {NGINX_PORT} default_server;
    server_name _;

    location / {{
        return 404 "Portal not found. If you recently signed up, your portal may still be initializing. Try again in a few minutes.\\n";
        add_header Content-Type text/plain;
    }}
}}
""")

    for subdomain, route in routes.items():
        portal_url = route.get('portal_url', '')
        if portal_url:
            blocks.append(_generate_customer_block(subdomain, portal_url))

    return '\n'.join(blocks)


def _generate_main_conf() -> str:
    """Generate the main purebrain nginx conf for portal.purebrain.ai."""
    return f"""# PureBrain Main Nginx Config
# Generated by subdomain_router.py
# portal.purebrain.ai → admin portal on port {ADMIN_PORTAL_PORT}

server {{
    listen {NGINX_PORT};
    server_name portal.purebrain.ai;

    # Increase timeouts for long-lived WebSocket connections
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

    location / {{
        proxy_pass http://127.0.0.1:{ADMIN_PORTAL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_cache off;
    }}
}}
"""


# ---------------------------------------------------------------------------
# nginx reload
# ---------------------------------------------------------------------------

def _sudo_write(path: Path, content: str) -> tuple[bool, str]:
    """Write file content using sudo tee (required for root-owned nginx conf.d)."""
    result = subprocess.run(
        ['sudo', 'tee', str(path)],
        input=content, text=True,
        capture_output=True
    )
    if result.returncode != 0:
        return False, f"sudo tee failed for {path}: {result.stderr}"
    return True, f"Wrote {path}"


def write_and_reload_nginx(routes: dict) -> tuple[bool, str]:
    """Write nginx configs and reload. Returns (success, message)."""
    try:
        # Write customer portals conf (requires sudo for /etc/nginx/conf.d/)
        customer_conf = _generate_nginx_conf(routes)
        ok, msg = _sudo_write(NGINX_CUSTOMER_CONF, customer_conf)
        if not ok:
            return False, msg

        # Write main conf (portal.purebrain.ai)
        ok, msg = _sudo_write(NGINX_MAIN_CONF, _generate_main_conf())
        if not ok:
            return False, msg

        # Test nginx config first
        result = subprocess.run(
            ['sudo', 'nginx', '-t'],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            return False, f"nginx config test failed:\n{result.stderr}"

        # Reload nginx (graceful — no connection drops)
        result = subprocess.run(
            ['sudo', 'systemctl', 'reload', 'nginx'],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            return False, f"nginx reload failed:\n{result.stderr}"

        return True, "nginx config written and reloaded successfully"

    except Exception as e:
        return False, f"Error: {e}"


# ---------------------------------------------------------------------------
# Cloudflare DNS management
# ---------------------------------------------------------------------------

def add_cloudflare_dns(subdomain: str) -> tuple[bool, str]:
    """Add CNAME DNS record for subdomain.purebrain.ai via cloudflared.

    Creates: {subdomain}.purebrain.ai CNAME → tunnel endpoint
    Requires sudo (tunnel credentials are root-owned).
    """
    fqdn = f"{subdomain}.purebrain.ai"
    try:
        result = subprocess.run(
            ['sudo', 'cloudflared', 'tunnel', 'route', 'dns', TUNNEL_ID, fqdn],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return True, f"DNS CNAME created: {fqdn}"
        # Cloudflared exits 1 if record already exists but that's fine
        stderr = result.stderr.lower()
        if 'already' in stderr or 'exists' in stderr or 'duplicate' in stderr:
            return True, f"DNS record already exists for {fqdn}"
        return False, f"cloudflared DNS failed:\n{result.stderr}"
    except subprocess.TimeoutExpired:
        return False, "cloudflared DNS command timed out"
    except Exception as e:
        return False, f"Error creating DNS: {e}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def add_customer_route(
    subdomain: str,
    portal_url: str,
    container: str = '',
    human_email: str = '',
    human_name: str = '',
    civ_name: str = '',
) -> tuple[bool, str]:
    """
    Add a new customer portal route.

    Called by purebrain_log_server.py on birth_complete webhook.

    Args:
        subdomain: e.g. "keenjared" (will become keenjared.purebrain.ai)
        portal_url: e.g. "https://keenjared.ai-civ.com"
        container: e.g. "aiciv-12"
        human_email: customer email
        human_name: customer full name
        civ_name: AI name (e.g. "keen")

    Returns:
        (success: bool, message: str)
    """
    # Validate subdomain — only alphanumeric + hyphens, no dots
    if not re.match(r'^[a-z0-9][a-z0-9\-]*$', subdomain):
        return False, f"Invalid subdomain: {subdomain!r}. Must be lowercase alphanumeric + hyphens."

    # Validate portal_url
    if not portal_url.startswith(('http://', 'https://')):
        return False, f"Invalid portal_url: {portal_url!r}"

    routes = load_routes()

    # Add or update route
    routes[subdomain] = {
        'subdomain': subdomain,
        'portal_url': portal_url,
        'container': container,
        'human_email': human_email,
        'human_name': human_name,
        'civ_name': civ_name,
        'purebrain_url': f"https://{subdomain}.purebrain.ai",
        'created_at': datetime.now(timezone.utc).isoformat(),
    }
    save_routes(routes)

    # Write nginx config and reload
    ok, msg = write_and_reload_nginx(routes)
    if not ok:
        return False, f"Route saved but nginx failed: {msg}"

    # Add Cloudflare DNS (idempotent — safe to call even if exists)
    dns_ok, dns_msg = add_cloudflare_dns(subdomain)

    result_msg = (
        f"Route added: https://{subdomain}.purebrain.ai → {portal_url}\n"
        f"nginx: {msg}\n"
        f"DNS: {dns_msg}"
    )
    return True, result_msg


def remove_customer_route(subdomain: str) -> tuple[bool, str]:
    """Remove a customer portal route and reload nginx."""
    routes = load_routes()
    if subdomain not in routes:
        return False, f"Subdomain not found: {subdomain}"

    del routes[subdomain]
    save_routes(routes)

    ok, msg = write_and_reload_nginx(routes)
    return ok, f"Route removed: {subdomain}.purebrain.ai\nnginx: {msg}"


def list_routes() -> list[dict]:
    """Return all current routes."""
    return list(load_routes().values())


def status() -> dict:
    """Return status summary."""
    routes = load_routes()
    return {
        'total_routes': len(routes),
        'routes': list(routes.keys()),
        'nginx_conf': str(NGINX_CUSTOMER_CONF),
        'routes_file': str(ROUTES_FILE),
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cmd_add(args):
    if len(args) < 2:
        print("Usage: subdomain_router.py add <subdomain> <portal_url> [container] [email] [human_name] [civ_name]")
        sys.exit(1)
    subdomain = args[0].lower()
    portal_url = args[1]
    container = args[2] if len(args) > 2 else ''
    email = args[3] if len(args) > 3 else ''
    human_name = args[4] if len(args) > 4 else ''
    civ_name = args[5] if len(args) > 5 else ''

    ok, msg = add_customer_route(subdomain, portal_url, container, email, human_name, civ_name)
    print(msg)
    sys.exit(0 if ok else 1)


def _cmd_remove(args):
    if not args:
        print("Usage: subdomain_router.py remove <subdomain>")
        sys.exit(1)
    ok, msg = remove_customer_route(args[0])
    print(msg)
    sys.exit(0 if ok else 1)


def _cmd_list():
    routes = list_routes()
    if not routes:
        print("No customer routes configured.")
        return
    print(f"{'Subdomain':<30} {'Container':<15} {'Portal URL'}")
    print('-' * 80)
    for r in routes:
        print(f"{r['subdomain'] + '.purebrain.ai':<30} {r.get('container',''):<15} {r.get('portal_url','')}")


def _cmd_reload():
    routes = load_routes()
    ok, msg = write_and_reload_nginx(routes)
    print(msg)
    sys.exit(0 if ok else 1)


def _cmd_status():
    s = status()
    print(f"Total routes: {s['total_routes']}")
    print(f"Routes file: {s['routes_file']}")
    print(f"nginx conf: {s['nginx_conf']}")
    if s['routes']:
        print(f"Active subdomains: {', '.join(s['routes'])}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    cmd = sys.argv[1]
    rest = sys.argv[2:]

    if cmd == 'add':
        _cmd_add(rest)
    elif cmd == 'remove':
        _cmd_remove(rest)
    elif cmd == 'list':
        _cmd_list()
    elif cmd == 'reload-nginx':
        _cmd_reload()
    elif cmd == 'status':
        _cmd_status()
    else:
        print(f"Unknown command: {cmd}")
        print("Commands: add, remove, list, reload-nginx, status")
        sys.exit(1)
